### ISSUE TITLE
🐛 Meting API 失效导致播放器无法播放

### ISSUE THREAD

**Issue by demigodliu** [moefyit/vuepress-plugin-meting#26]
截图：https://i.loli.net/2021/06/22/9TsV3QDGUrMLAE8.png

**Comment by demigodliu** [comment]
地址：https://moefyit.github.io/moefy-vuepress/packages/meting.html#install

**Comment by SigureMo** [comment]
API 出问题了，[MetingJS#56](https://github.com/metowolf/MetingJS/issues/56), [MetingJS#58](https://github.com/metowolf/MetingJS/issues/58) 中都提到这个问题，等待 API 修复吧，如果等不及可以自己参考 [Meting](https://github.com/metowolf/Meting) 研究并修复一下，甚至可以自行搭建，然后把插件 options 里的 metingApi 替换下就行了

**Comment by SigureMo** [comment]
https://github.com/metowolf/MetingJS/issues/56#issuecomment-869131600

API 问题已解决
