### ISSUE TITLE
请问vite 如何使用这个插件

### ISSUE THREAD

**Issue by YAANLE** [moefyit/vuepress-plugin-meting#27]

**Comment by SigureMo** [comment]
vite？你是说基于可选 vite 作为 dev server 的 vuepress2 吗？如果是这样的话那么很遗憾，本插件只支持 vuepress1，vuepress2 的话以后可能会支持。

或者说你是想要用 vite 开发 vue 项目吗，那直接使用 [vue-aplayer](https://github.com/MoePlayer/vue-aplayer) 就好了
