### ISSUE TITLE
网易云时不时无法获取列表

### ISSUE THREAD

**Issue by vlssu** [moefyit/vuepress-plugin-meting#28]
![image](https://user-images.githubusercontent.com/43847794/128971828-0fe3bcc4-c396-4389-9745-d2a24940c969.png)
这种现象已经好几次了。能修复吗？，感谢

**Comment by SigureMo** [comment]
这个问题我修复不了啊，这是 Meting API 的问题……可以试试自行搭建 API 看看能不能解决？

**Comment by vlssu** [comment]
> 这个问题我修复不了啊，这是 Meting API 的问题……可以试试自行搭建 API 看看能不能解决？

我自行搭建了，但是依旧如此。明明只从api去访问的话是可以的，但是用在插件上就用不了

https://api.vlssu.com/meting/
这是我自己搭建的API，是这个API没错吧？

**Comment by SigureMo** [comment]
嗯，API 本身没问题，但有配置跨域吗，我这里使用 localhost:8080 会提示跨域问题

![image](https://user-images.githubusercontent.com/38436475/129015316-1c7e12fa-abff-4655-86a6-63736e2176fd.png)

**Comment by vlssu** [comment]
> 嗯，API 本身没问题，但有配置跨域吗，我这里使用 localhost:8080 会提示跨域问题
> 
> ![image](https://user-images.githubusercontent.com/38436475/129015316-1c7e12fa-abff-4655-86a6-63736e2176fd.png)

我将跨域关闭了，但是依旧出现这种情况

**Comment by vlssu** [comment]
主要是有点离奇，时不时出现用不了的情况，而不是就是用不了，
但api那边能正常工作，所以有点想不通到是什么情况导致这种情况

**Comment by vlssu** [comment]
> 问题我这里已经解决了，见最新的 commit，之前我没想到你用的这个 meting-api 与 metowolf 提供的格式不同，所以会有这个问题，最新版本是支持 [meting-api](https://github.com/injahow/meting-api) 的，直接使用其 demo （`https://api.injahow.cn/meting/`） 是可以**完全正常工作**的（注意填写 `metingApi` 时最后要带 `/`）
> 
> 同样我也试了下你的 API，在最后带 `/` 也即填写 `metingApi` 为 `https://api.vlssu.com/meting/` 时，可以正常解析列表，但无法正常解析歌词，仍然提示跨域问题，若不带 `/` 也即填写为 `https://api.vlssu.com/meting` 时，连列表都因为跨域而无法正常解析，我怀疑你那里跨域配置仍有部分问题，你看看能否解决？
> 
> 我这里发布到 npm 这一步暂时出了点问题，如果有时间的话可以参考 github 上最新一步 commit 修改 node_modules 里的文件，测试一下效果。

好的我这里尝试下

**Comment by SigureMo** [comment]
emmm，换了台电脑成功 publish 了，你直接更新试试

**Comment by vlssu** [comment]
> emmm，换了台电脑成功 publish 了，你直接更新试试

好家伙，ok我试试

**Comment by SigureMo** [comment]
那你试试直接在你的博客里用这个 demo？这个 demo 的稳定性我不太清楚，我把[文档里的示例](https://moefyit.github.io/moefy-vuepress/packages/meting.html)所使用的 API 改成那个 demo 后可以正常使用了

我看了下你的 API 和 demo API 的解析结果，仔细比较可以发现还是有一点不一样的，就是 demo 解析出来的所有 url 都带有 `/`，所以不会有这个跨域问题，而你的 API 就没有，我怀疑是某个地方配置错了？

![image](https://user-images.githubusercontent.com/38436475/129035011-93753d68-f4a8-43e2-94c5-eb96540da933.png)

![image](https://user-images.githubusercontent.com/38436475/129035108-c0846069-0213-4a4e-b708-9a5ab8ce50bf.png)

**Comment by vlssu** [comment]
> 那你试试直接在你的博客里用这个 demo？这个 demo 的稳定性我不太清楚，我把[文档里的示例](https://moefyit.github.io/moefy-vuepress/packages/meting.html)所使用的 API 改成那个 demo 后可以正常工作了
> 
> 我看了下你的 API 和 demo API 的解析结果，仔细比较可以发现还是有一点不一样的，就是 demo 解析出来的所有 url 都带有 `/`，所以不会有这个跨域问题，而你的 API 就没有，我怀疑是某个地方配置错了？
> 
> ![image](https://user-images.githubusercontent.com/38436475/129035011-93753d68-f4a8-43e2-94c5-eb96540da933.png)
> 
> ![image](https://user-images.githubusercontent.com/38436475/129035108-c0846069-0213-4a4e-b708-9a5ab8ce50bf.png)

解决了，被你说对了，api本身设置的路径没有设置`/`吗，我当时因为出问题修改了下，忘记改回来了，忘记了这茬，被你一语惊醒。谢谢！！！我终于解决了这个骚问题

**Comment by vlssu** [comment]
还是有一个小小的问题，之前vip音乐能听到全部，现在只能听1分钟，甚至半分钟
