### ISSUE TITLE
The picture loading is abnormal when there is no incoming audio.

### ISSUE THREAD

**Issue by MoeCinnamo** [moefyit/vuepress-plugin-meting#34]
It is recommended to add a function that has no audio pictures to customize.

**Comment by MoeCinnamo** [comment]
It is best to remove anything that uses jsdelivr. It's too unstable.

**Comment by SigureMo** [comment]
> It is best to remove anything that uses jsdelivr. It's too unstable.

jsdelivr？指的是什么？我不清楚哪里有访问过 jsdelivr 的资源

> It is recommended to add a function that has no audio pictures to customize.

不显示图片吗？emmm，就 VueAplayer 而言没看到暴露相关 API，我也做不到啊……

**Comment by MoeCinnamo** [comment]
> > It is best to remove anything that uses jsdelivr. It's too unstable.
> 
> jsdelivr？指的是什么？我不清楚哪里有访问过 jsdelivr 的资源
> 
> > It is recommended to add a function that has no audio pictures to customize.
> 
> 不显示图片吗？emmm，就 VueAplayer 而言没看到暴露相关 API，我也做不到啊……

你的头像时调用的jsdelivr的资源，所以可以删除或者修改成其它的。

**Comment by SigureMo** [comment]
我的头像是 GitHub 资源(`https://github.com/SigureMo.png`)，不是 jsdelivr，删掉的话默认值是 vue-aplayer 作者 u3u 的头像 `https://github.com/u3u.png`，如果你无法访问前者的话，这个也同样访问不了

<https://nyakku.moe/avatar.jpg> 这个你可以访问吗

**Comment by MoeCinnamo** [comment]
这三个全都是可以访问的，但是资源报错也确实指向jsdelivr。

有的时候显示

https://avatars.githubusercontent.com/u/38436475?v=4

也有可能是其它插件问题

**Comment by MoeCinnamo** [comment]
对于出现问题的时候，图片将无法进行正常加载。

**Comment by SigureMo** [comment]
我刚刚发布了 0.3.2，允许自定义默认封面图，你可以试一下

```javascript
// .vuepress/config.js
module.exports = {
   plugins: [
      'meting',
      {
         // 这个 API 是不可用的，只是作为示例而已
         metingApi: 'https://meting.example.com/api/',
         meting: {
            server: 'netease',
            type: 'playlist',
            mid: '6838211960',
         }, // 不配置该项的话不会出现全局播放器
         aplayer: {
            lrcType: 3,
         },
         defaultCover: 'https://nyakku.moe/avatar.jpg', // <--- 这里
      },
   ],
}
```

**Comment by MoeCinnamo** [comment]
> 我刚刚发布了 0.3.2，允许自定义默认封面图，你可以试一下
> 
> ```js
> // .vuepress/config.js
> module.exports = {
>    plugins: [
>       'meting',
>       {
>          // 这个 API 是不可用的，只是作为示例而已
>          metingApi: 'https://meting.example.com/api/',
>          meting: {
>             server: 'netease',
>             type: 'playlist',
>             mid: '6838211960',
>          }, // 不配置该项的话不会出现全局播放器
>          aplayer: {
>             lrcType: 3,
>          },
>          defaultCover: 'https://nyakku.moe/avatar.jpg', // <--- 这里
>       },
>    ],
> }
> ```

好的好的
