### ISSUE TITLE
酷狗音乐歌单如何使用

### ISSUE THREAD

**Issue by MoeCinnamo** [moefyit/vuepress-plugin-meting#35]
我的酷狗音乐歌单链接：https://t1.kugou.com/song.html?id=uf7AcfzAV3

请问它如何才能使用。

**Comment by MoeCinnamo** [comment]
这里一共有80首，被和谐了一首。请问怎么才能用meting调用它来播放它里面的歌曲列表。

多期连在一起播放，默认播放最新的，然后播放老的。

**Comment by SigureMo** [comment]
我不清楚你说的 80 首是什么，我这里只能看到 31 首的播放队列。

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/38436475/172578631-c95b7d14-5e7a-446b-bab2-cfd86ab53c2e.png">

关于酷狗，我没有用过，因此我也无法解答，由于这是 API 问题，所以相关问题请查看 <https://github.com/metowolf/Meting>

先 close 了，如果确认这是插件问题而不是 API 问题，可以随意 reopen

**Comment by MoeCinnamo** [comment]
> 我不清楚你说的 80 首是什么，我这里只能看到 31 首的播放队列。
> 
> <img alt="image" width="1004" src="https://user-images.githubusercontent.com/38436475/172578631-c95b7d14-5e7a-446b-bab2-cfd86ab53c2e.png">
> 
> 关于酷狗，我没有用过，因此我也无法解答，由于这是 API 问题，所以相关问题请查看 https://github.com/metowolf/Meting
> 
> 先 close 了，如果 **确认这是插件问题（issue）** 而不是 API 问题，可以随意 reopen

好的，可能又被和谐了，或者有些会员的不能放
